const dataArray = [
  {
    name: "Dorry Beviss",
    gender: "Female",
    email: "dbeviss0@uiuc.edu",
    id: 1,
    scores: [63, 55, 45, 70, 52],
  },
  {
    name: "Julita Skiggs",
    gender: "Female",
    email: "jskiggs1@arizona.edu",
    id: 2,
    scores: [88, 88, 92, 90, 95],
  },
  {
    name: "Ermina Geraldini",
    gender: "Female",
    email: "egeraldini2@google.nl",
    id: 3,
    scores: [22, 36, 10, 25, 40],
  },
  {
    name: "Forrest Stapleton",
    gender: "Male",
    email: "fstapleton3@hatena.ne.jp",
    id: 4,
    scores: [82, 70, 65, 72, 50],
  },
  {
    name: "Arabele Mallebone",
    gender: "Female",
    email: "amallebone4@sohu.com",
    id: 5,
    scores: [85, 90, 82, 80, 59],
  },
  {
    name: "Lona Groneway",
    gender: "Female",
    email: "lgroneway5@ucsd.edu",
    id: 6,
    scores: [48, 52, 27, 55, 45],
  },
  {
    name: "Jeddy Richardt",
    gender: "Male",
    email: "jrichardt6@fastcompany.com",
    id: 7,
    scores: [46, 66, 46, 78, 55],
  },
  {
    name: "Letta Platt",
    gender: "Male",
    email: "lplatt7@slideshare.net",
    id: 8,
    scores: [78, 82, 85, 90, 70],
  },
  {
    name: "Nanny Proger",
    gender: "Female",
    email: "nproger8@fotki.com",
    id: 9,
    scores: [78, 59, 80, 60, 75],
  },
  {
    name: "Prissie Filintsev",
    gender: "Female",
    email: "pfilintsev9@alexa.com",
    id: 10,
    scores: [20, 40, 15, 20, 35],
  },
];
